// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  content_with_image: dynamic(() => import("./ContentWithImage")),
  footer: dynamic(() => import("./Footer")),
  hero: dynamic(() => import("./Hero")),
  products_grid: dynamic(() => import("./ProductsGrid")),
};
