// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  brands: dynamic(() => import("./Brands")),
  content_with_image: dynamic(() => import("./ContentWithImage")),
  corportation_data: dynamic(() => import("./CorportationData")),
  features: dynamic(() => import("./Features")),
  hero: dynamic(() => import("./Hero")),
  product_slice: dynamic(() => import("./ProductGrid")),
  products: dynamic(() => import("./Products")),
  quality_description: dynamic(() => import("./QualityDescription")),
  quality_feature: dynamic(() => import("./QualityFeature")),
  state_and_form: dynamic(() => import("./StateAndForm")),
  values: dynamic(() => import("./Values")),
};
